# Setup
title:               Yousuf's Blog
tagline:             'Sharing what I know.'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://yousufsaif.github.io
baseurl:             ''
paginate:            6
permalink:           pretty

# About/contact
author:
  name:              Yousuf Saif Al Hinai
  url:               https://twitter.com/yousufalhinai
  email:             yousuf_saif@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
